<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\BulkImportBatchStatus;
use App\Repository\BulkImportBatchRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * BulkImportBatch — audit-trail anchor for a single bulk-import operation.
 *
 * Implements hybrid audit-pattern (ISO 27001 Clause 7.5.3): one batch entry
 * per import + N per-row entries referencing batch_id, persisted via
 * AuditLogger::logBulk() (CC3 Sprint 0).
 *
 * Source-file retention: original CSV/XLSX persisted as Document
 * (documentType='import_evidence'), linked via $sourceDocument.
 */
#[ORM\Entity(repositoryClass: BulkImportBatchRepository::class)]
#[ORM\Table(name: 'bulk_import_batch')]
#[ORM\Index(columns: ['tenant_id', 'created_at'], name: 'idx_bulk_import_batch_tenant_created')]
#[ORM\Index(columns: ['entity_type'], name: 'idx_bulk_import_batch_entity_type')]
class BulkImportBatch
{
    public const MODE_INITIAL = 'initial';
    public const MODE_DELTA = 'delta';
    public const MODE_DRY_RUN = 'dry_run';

    public const STATUS_UPLOADED = 'uploaded';
    public const STATUS_MAPPED = 'mapped';
    public const STATUS_PREVIEW = 'preview';
    public const STATUS_COMMITTING = 'committing';
    public const STATUS_COMPLETED = 'completed';
    public const STATUS_FAILED = 'failed';
    public const STATUS_CANCELLED = 'cancelled';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Tenant::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tenant $tenant = null;

    /**
     * Entity-class short-name being imported: Asset / Supplier / Control / Risk / BusinessProcess.
     */
    #[ORM\Column(length: 64)]
    private string $entityType;

    /**
     * UUIDv4 generated by AuditLogger::logBulk() to correlate batch + per-entity entries.
     */
    #[ORM\Column(length: 36, unique: true, nullable: true)]
    private ?string $batchId = null;

    #[ORM\Column(length: 16)]
    private string $mode = self::MODE_INITIAL;

    #[ORM\Column(length: 32)]
    private string $status = self::STATUS_UPLOADED;

    /**
     * Original upload filename (display-only).
     */
    #[ORM\Column(length: 255)]
    private string $sourceFileName;

    /**
     * SHA-256 hash of the uploaded file for tamper-evidence + dedup.
     */
    #[ORM\Column(length: 64)]
    private string $sourceFileHash;

    #[ORM\Column(type: Types::BIGINT)]
    private string $sourceFileSize = '0';

    /**
     * Source document (type=import_evidence) retaining the original file.
     */
    #[ORM\ManyToOne(targetEntity: Document::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?Document $sourceDocument = null;

    /**
     * Hash of the dry-run preview output for reproducibility.
     */
    #[ORM\Column(length: 64, nullable: true)]
    private ?string $dryRunResultHash = null;

    /**
     * Column-mapping confirmed by user: {sourceColumn => entityField}.
     */
    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $columnMapping = null;

    #[ORM\Column]
    private int $rowCountTotal = 0;

    #[ORM\Column]
    private int $rowCountSuccess = 0;

    #[ORM\Column]
    private int $rowCountSkipped = 0;

    #[ORM\Column]
    private int $rowCountError = 0;

    #[ORM\Column]
    private int $rowCountUpdated = 0;

    /**
     * Free-form notes captured during import (e.g. last-error-message).
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $executedBy = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $committedAt = null;

    /**
     * @var Collection<int, BulkImportRow>
     */
    #[ORM\OneToMany(mappedBy: 'batch', targetEntity: BulkImportRow::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $rows;

    public function __construct()
    {
        $this->rows = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTenant(): ?Tenant
    {
        return $this->tenant;
    }

    public function setTenant(?Tenant $tenant): static
    {
        $this->tenant = $tenant;
        return $this;
    }

    public function getEntityType(): string
    {
        return $this->entityType;
    }

    public function setEntityType(string $entityType): static
    {
        $this->entityType = $entityType;
        return $this;
    }

    public function getBatchId(): ?string
    {
        return $this->batchId;
    }

    public function setBatchId(?string $batchId): static
    {
        $this->batchId = $batchId;
        return $this;
    }

    public function getMode(): string
    {
        return $this->mode;
    }

    public function setMode(string $mode): static
    {
        $this->mode = $mode;
        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(BulkImportBatchStatus|string $status): static
    {
        // Accept both enum and string so new code can pass the typed enum
        // while existing string-passing callers keep working unchanged.
        $this->status = is_string($status) ? $status : $status->value;
        return $this;
    }

    /** Typed status surface for enum-aware code. */
    public function getStatusEnum(): ?BulkImportBatchStatus
    {
        return BulkImportBatchStatus::tryFrom($this->status);
    }

    public function getSourceFileName(): string
    {
        return $this->sourceFileName;
    }

    public function setSourceFileName(string $sourceFileName): static
    {
        $this->sourceFileName = $sourceFileName;
        return $this;
    }

    public function getSourceFileHash(): string
    {
        return $this->sourceFileHash;
    }

    public function setSourceFileHash(string $sourceFileHash): static
    {
        $this->sourceFileHash = $sourceFileHash;
        return $this;
    }

    public function getSourceFileSize(): string
    {
        return $this->sourceFileSize;
    }

    public function setSourceFileSize(string $sourceFileSize): static
    {
        $this->sourceFileSize = $sourceFileSize;
        return $this;
    }

    public function getSourceDocument(): ?Document
    {
        return $this->sourceDocument;
    }

    public function setSourceDocument(?Document $sourceDocument): static
    {
        $this->sourceDocument = $sourceDocument;
        return $this;
    }

    public function getDryRunResultHash(): ?string
    {
        return $this->dryRunResultHash;
    }

    public function setDryRunResultHash(?string $dryRunResultHash): static
    {
        $this->dryRunResultHash = $dryRunResultHash;
        return $this;
    }

    public function getColumnMapping(): ?array
    {
        return $this->columnMapping;
    }

    public function setColumnMapping(?array $columnMapping): static
    {
        $this->columnMapping = $columnMapping;
        return $this;
    }

    public function getRowCountTotal(): int
    {
        return $this->rowCountTotal;
    }

    public function setRowCountTotal(int $rowCountTotal): static
    {
        $this->rowCountTotal = $rowCountTotal;
        return $this;
    }

    public function getRowCountSuccess(): int
    {
        return $this->rowCountSuccess;
    }

    public function setRowCountSuccess(int $rowCountSuccess): static
    {
        $this->rowCountSuccess = $rowCountSuccess;
        return $this;
    }

    public function getRowCountSkipped(): int
    {
        return $this->rowCountSkipped;
    }

    public function setRowCountSkipped(int $rowCountSkipped): static
    {
        $this->rowCountSkipped = $rowCountSkipped;
        return $this;
    }

    public function getRowCountError(): int
    {
        return $this->rowCountError;
    }

    public function setRowCountError(int $rowCountError): static
    {
        $this->rowCountError = $rowCountError;
        return $this;
    }

    public function getRowCountUpdated(): int
    {
        return $this->rowCountUpdated;
    }

    public function setRowCountUpdated(int $rowCountUpdated): static
    {
        $this->rowCountUpdated = $rowCountUpdated;
        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;
        return $this;
    }

    public function getExecutedBy(): ?User
    {
        return $this->executedBy;
    }

    public function setExecutedBy(?User $executedBy): static
    {
        $this->executedBy = $executedBy;
        return $this;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getCommittedAt(): ?DateTimeImmutable
    {
        return $this->committedAt;
    }

    public function setCommittedAt(?DateTimeImmutable $committedAt): static
    {
        $this->committedAt = $committedAt;
        return $this;
    }

    /**
     * @return Collection<int, BulkImportRow>
     */
    public function getRows(): Collection
    {
        return $this->rows;
    }

    public function addRow(BulkImportRow $row): static
    {
        if (!$this->rows->contains($row)) {
            $this->rows->add($row);
            $row->setBatch($this);
        }
        return $this;
    }

    public function removeRow(BulkImportRow $row): static
    {
        if ($this->rows->removeElement($row) && $row->getBatch() === $this) {
            $row->setBatch(null);
        }
        return $this;
    }

    public function isCompleted(): bool
    {
        return $this->status === self::STATUS_COMPLETED;
    }

    public function isDeltaMode(): bool
    {
        return $this->mode === self::MODE_DELTA;
    }
}
