<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251113140643 extends AbstractMigration
{
    /**
     * DDL migration — MySQL implicitly commits ALTER/CREATE/DROP which
     * invalidates Doctrine's per-migration SAVEPOINT (CLAUDE.md Pitfall #6).
     */
    public function isTransactional(): bool
    {
        return false;
    }

    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, asset_type VARCHAR(100) NOT NULL, owner VARCHAR(100) NOT NULL, location VARCHAR(100) DEFAULT NULL, acquisition_value NUMERIC(10, 2) DEFAULT NULL, current_value NUMERIC(10, 2) DEFAULT NULL, confidentiality_value INT NOT NULL, integrity_value INT NOT NULL, availability_value INT NOT NULL, monetary_value NUMERIC(15, 2) DEFAULT NULL, data_classification VARCHAR(50) DEFAULT NULL, acceptable_use_policy LONGTEXT DEFAULT NULL, handling_instructions LONGTEXT DEFAULT NULL, return_date DATE DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, physical_location_id INT DEFAULT NULL, INDEX IDX_2AF5A5CB5B8AA78 (physical_location_id), INDEX idx_asset_type (asset_type), INDEX idx_asset_status (status), INDEX idx_asset_created_at (created_at), INDEX idx_asset_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE audit_checklist (id INT AUTO_INCREMENT NOT NULL, verification_status VARCHAR(50) NOT NULL, audit_notes LONGTEXT DEFAULT NULL, evidence_found LONGTEXT DEFAULT NULL, findings LONGTEXT DEFAULT NULL, recommendations LONGTEXT DEFAULT NULL, compliance_score INT NOT NULL, auditor VARCHAR(100) DEFAULT NULL, verified_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, audit_id INT NOT NULL, requirement_id INT NOT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_85EF23A0BD29F359 (audit_id), INDEX IDX_85EF23A07B576F77 (requirement_id), INDEX IDX_85EF23A09033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE audit_log (id INT AUTO_INCREMENT NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id INT DEFAULT NULL, action VARCHAR(50) NOT NULL, user_name VARCHAR(100) NOT NULL, ip_address VARCHAR(100) DEFAULT NULL, old_values LONGTEXT DEFAULT NULL, new_values LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, INDEX idx_entity (entity_type, entity_id), INDEX idx_user (user_name), INDEX idx_action (action), INDEX idx_created_at (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bc_exercise (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, exercise_type VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, scope LONGTEXT NOT NULL, objectives LONGTEXT NOT NULL, scenario LONGTEXT DEFAULT NULL, exercise_date DATE NOT NULL, duration_hours INT DEFAULT NULL, participants LONGTEXT NOT NULL, facilitator VARCHAR(100) NOT NULL, observers LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, results LONGTEXT DEFAULT NULL, what_went_well LONGTEXT DEFAULT NULL, areas_for_improvement LONGTEXT DEFAULT NULL, findings LONGTEXT DEFAULT NULL, action_items LONGTEXT DEFAULT NULL, lessons_learned LONGTEXT DEFAULT NULL, plan_updates_required LONGTEXT DEFAULT NULL, success_criteria JSON DEFAULT NULL, success_rating INT DEFAULT NULL, report_completed TINYINT(1) NOT NULL, report_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX idx_bc_exercise_type (exercise_type), INDEX idx_bc_exercise_date (exercise_date), INDEX idx_bc_exercise_status (status), INDEX idx_bc_exercise_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bc_exercise_plan (bcexercise_id INT NOT NULL, business_continuity_plan_id INT NOT NULL, INDEX IDX_FB8DCC0DBCA4B399 (bcexercise_id), INDEX IDX_FB8DCC0DE338D05C (business_continuity_plan_id), PRIMARY KEY (bcexercise_id, business_continuity_plan_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bc_exercise_document (bcexercise_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_577E52BABCA4B399 (bcexercise_id), INDEX IDX_577E52BAC33F7837 (document_id), PRIMARY KEY (bcexercise_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE business_continuity_plan (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, plan_owner VARCHAR(100) NOT NULL, bc_team LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, activation_criteria LONGTEXT NOT NULL, roles_and_responsibilities LONGTEXT DEFAULT NULL, response_team JSON DEFAULT NULL, recovery_procedures LONGTEXT NOT NULL, communication_plan LONGTEXT DEFAULT NULL, internal_communication LONGTEXT DEFAULT NULL, external_communication LONGTEXT DEFAULT NULL, stakeholder_contacts JSON DEFAULT NULL, alternative_site LONGTEXT DEFAULT NULL, alternative_site_address LONGTEXT DEFAULT NULL, alternative_site_capacity LONGTEXT DEFAULT NULL, backup_procedures LONGTEXT DEFAULT NULL, restore_procedures LONGTEXT DEFAULT NULL, required_resources JSON DEFAULT NULL, version VARCHAR(20) NOT NULL, last_tested DATE DEFAULT NULL, next_test_date DATE DEFAULT NULL, last_review_date DATE DEFAULT NULL, next_review_date DATE DEFAULT NULL, review_notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, business_process_id INT NOT NULL, INDEX IDX_BC771CE6BE61FDDF (business_process_id), INDEX idx_bc_plan_status (status), INDEX idx_bc_plan_last_tested (last_tested), INDEX idx_bc_plan_next_review (next_review_date), INDEX idx_bc_plan_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bc_plan_supplier (business_continuity_plan_id INT NOT NULL, supplier_id INT NOT NULL, INDEX IDX_EABDAEC6E338D05C (business_continuity_plan_id), INDEX IDX_EABDAEC62ADD6D8C (supplier_id), PRIMARY KEY (business_continuity_plan_id, supplier_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bc_plan_asset (business_continuity_plan_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_67D2C95BE338D05C (business_continuity_plan_id), INDEX IDX_67D2C95B5DA1941 (asset_id), PRIMARY KEY (business_continuity_plan_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bc_plan_document (business_continuity_plan_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_A9FE48CEE338D05C (business_continuity_plan_id), INDEX IDX_A9FE48CEC33F7837 (document_id), PRIMARY KEY (business_continuity_plan_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE business_process (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, process_owner VARCHAR(100) NOT NULL, criticality VARCHAR(50) NOT NULL, rto INT NOT NULL, rpo INT NOT NULL, mtpd INT NOT NULL, financial_impact_per_hour NUMERIC(10, 2) DEFAULT NULL, financial_impact_per_day NUMERIC(10, 2) DEFAULT NULL, reputational_impact INT NOT NULL, regulatory_impact INT NOT NULL, operational_impact INT NOT NULL, dependencies_upstream LONGTEXT DEFAULT NULL, dependencies_downstream LONGTEXT DEFAULT NULL, recovery_strategy LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_DB2EA3DB9033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE business_process_asset (business_process_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_6D8BDB6BE61FDDF (business_process_id), INDEX IDX_6D8BDB65DA1941 (asset_id), PRIMARY KEY (business_process_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE business_process_risk (business_process_id INT NOT NULL, risk_id INT NOT NULL, INDEX IDX_D5C72AC7BE61FDDF (business_process_id), INDEX IDX_D5C72AC7235B6D1 (risk_id), PRIMARY KEY (business_process_id, risk_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE change_request (id INT AUTO_INCREMENT NOT NULL, change_number VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, change_type VARCHAR(50) NOT NULL, description LONGTEXT NOT NULL, justification LONGTEXT NOT NULL, requested_by VARCHAR(100) NOT NULL, requested_date DATE NOT NULL, priority VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, isms_impact LONGTEXT DEFAULT NULL, risk_assessment LONGTEXT DEFAULT NULL, implementation_plan LONGTEXT DEFAULT NULL, rollback_plan LONGTEXT DEFAULT NULL, testing_requirements LONGTEXT DEFAULT NULL, planned_implementation_date DATE DEFAULT NULL, actual_implementation_date DATE DEFAULT NULL, approved_by VARCHAR(100) DEFAULT NULL, approved_date DATE DEFAULT NULL, approval_comments LONGTEXT DEFAULT NULL, implemented_by VARCHAR(100) DEFAULT NULL, implementation_notes LONGTEXT DEFAULT NULL, verified_by VARCHAR(100) DEFAULT NULL, verified_date DATE DEFAULT NULL, verification_results LONGTEXT DEFAULT NULL, closed_date DATE DEFAULT NULL, closure_notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX idx_change_type (change_type), INDEX idx_change_priority (priority), INDEX idx_change_status (status), INDEX idx_change_planned_date (planned_implementation_date), INDEX idx_change_request_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE change_request_asset (change_request_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_435F21C096829572 (change_request_id), INDEX IDX_435F21C05DA1941 (asset_id), PRIMARY KEY (change_request_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE change_request_control (change_request_id INT NOT NULL, control_id INT NOT NULL, INDEX IDX_F7F8001996829572 (change_request_id), INDEX IDX_F7F8001932BEC70E (control_id), PRIMARY KEY (change_request_id, control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE change_request_business_process (change_request_id INT NOT NULL, business_process_id INT NOT NULL, INDEX IDX_754BBFCE96829572 (change_request_id), INDEX IDX_754BBFCEBE61FDDF (business_process_id), PRIMARY KEY (change_request_id, business_process_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE change_request_risk (change_request_id INT NOT NULL, risk_id INT NOT NULL, INDEX IDX_8D0729EA96829572 (change_request_id), INDEX IDX_8D0729EA235B6D1 (risk_id), PRIMARY KEY (change_request_id, risk_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE change_request_document (change_request_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_5D16998296829572 (change_request_id), INDEX IDX_5D169982C33F7837 (document_id), PRIMARY KEY (change_request_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE compliance_framework (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, version VARCHAR(50) NOT NULL, applicable_industry VARCHAR(100) NOT NULL, regulatory_body VARCHAR(100) NOT NULL, mandatory TINYINT(1) NOT NULL, scope_description LONGTEXT DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_D57874E277153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE compliance_mapping (id INT AUTO_INCREMENT NOT NULL, mapping_percentage INT NOT NULL, mapping_type VARCHAR(50) NOT NULL, mapping_rationale LONGTEXT DEFAULT NULL, bidirectional TINYINT(1) NOT NULL, confidence VARCHAR(20) NOT NULL, verified_by VARCHAR(100) DEFAULT NULL, verification_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, source_requirement_id INT NOT NULL, target_requirement_id INT NOT NULL, INDEX IDX_3D5913BD82E03D2 (source_requirement_id), INDEX IDX_3D5913BC72D605E (target_requirement_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE compliance_requirement (id INT AUTO_INCREMENT NOT NULL, requirement_id VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, category VARCHAR(100) DEFAULT NULL, priority VARCHAR(50) NOT NULL, requirement_type VARCHAR(50) NOT NULL, applicable TINYINT(1) NOT NULL, applicability_justification LONGTEXT DEFAULT NULL, fulfillment_percentage INT NOT NULL, fulfillment_notes LONGTEXT DEFAULT NULL, evidence_description LONGTEXT DEFAULT NULL, data_source_mapping JSON DEFAULT NULL, responsible_person VARCHAR(100) DEFAULT NULL, target_date DATE DEFAULT NULL, last_assessment_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, framework_id INT NOT NULL, parent_requirement_id INT DEFAULT NULL, INDEX IDX_D115DC5237AECF72 (framework_id), INDEX IDX_D115DC52658A1B7C (parent_requirement_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE compliance_requirement_control (compliance_requirement_id INT NOT NULL, control_id INT NOT NULL, INDEX IDX_57D957D492951C7 (compliance_requirement_id), INDEX IDX_57D957D32BEC70E (control_id), PRIMARY KEY (compliance_requirement_id, control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE control (id INT AUTO_INCREMENT NOT NULL, control_id VARCHAR(20) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, category VARCHAR(100) NOT NULL, applicable TINYINT(1) NOT NULL, justification LONGTEXT DEFAULT NULL, implementation_notes LONGTEXT DEFAULT NULL, implementation_status VARCHAR(50) NOT NULL, implementation_percentage INT DEFAULT NULL, responsible_person VARCHAR(100) DEFAULT NULL, target_date DATE DEFAULT NULL, last_review_date DATE DEFAULT NULL, next_review_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX idx_control_control_id (control_id), INDEX idx_control_category (category), INDEX idx_control_impl_status (implementation_status), INDEX idx_control_target_date (target_date), INDEX idx_control_applicable (applicable), INDEX idx_control_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE control_risk (control_id INT NOT NULL, risk_id INT NOT NULL, INDEX IDX_8BE88BF432BEC70E (control_id), INDEX IDX_8BE88BF4235B6D1 (risk_id), PRIMARY KEY (control_id, risk_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE control_asset (control_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_B956F30132BEC70E (control_id), INDEX IDX_B956F3015DA1941 (asset_id), PRIMARY KEY (control_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE crisis_teams (id INT AUTO_INCREMENT NOT NULL, team_name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, team_type VARCHAR(30) NOT NULL, is_active TINYINT(1) NOT NULL, members JSON NOT NULL, primary_phone VARCHAR(50) DEFAULT NULL, primary_email VARCHAR(255) DEFAULT NULL, emergency_contacts JSON DEFAULT NULL, meeting_location LONGTEXT DEFAULT NULL, backup_meeting_location LONGTEXT DEFAULT NULL, virtual_meeting_url LONGTEXT DEFAULT NULL, alert_procedures LONGTEXT DEFAULT NULL, decision_authority LONGTEXT DEFAULT NULL, communication_protocols LONGTEXT DEFAULT NULL, available_resources JSON DEFAULT NULL, training_schedule LONGTEXT DEFAULT NULL, last_activated_at DATETIME DEFAULT NULL, last_training_at DATETIME DEFAULT NULL, next_training_at DATETIME DEFAULT NULL, documentation JSON DEFAULT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, team_leader_id INT DEFAULT NULL, deputy_leader_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_D9975D4EC4105033 (team_leader_id), INDEX IDX_D9975D4E42E65CAD (deputy_leader_id), INDEX IDX_D9975D4E9033212A (tenant_id), INDEX idx_crisis_team_name (team_name), INDEX idx_crisis_team_active (is_active), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE crisis_team_bcp (crisis_team_id INT NOT NULL, business_continuity_plan_id INT NOT NULL, INDEX IDX_5B591A6FF54E4E81 (crisis_team_id), INDEX IDX_5B591A6FE338D05C (business_continuity_plan_id), PRIMARY KEY (crisis_team_id, business_continuity_plan_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cryptographic_operation (id INT AUTO_INCREMENT NOT NULL, operation_type VARCHAR(50) NOT NULL, algorithm VARCHAR(100) NOT NULL, key_length INT DEFAULT NULL, key_identifier VARCHAR(255) DEFAULT NULL, purpose LONGTEXT DEFAULT NULL, data_classification VARCHAR(255) DEFAULT NULL, application_component VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, error_message LONGTEXT DEFAULT NULL, timestamp DATETIME NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, metadata LONGTEXT DEFAULT NULL, compliance_relevant TINYINT(1) NOT NULL, user_id INT DEFAULT NULL, related_asset_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_9E980109A35957EC (related_asset_id), INDEX IDX_9E9801099033212A (tenant_id), INDEX idx_crypto_operation_type (operation_type), INDEX idx_crypto_timestamp (timestamp), INDEX idx_crypto_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT NOT NULL, file_path VARCHAR(500) NOT NULL, category VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, entity_type VARCHAR(100) DEFAULT NULL, entity_id INT DEFAULT NULL, uploaded_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, sha256_hash VARCHAR(64) DEFAULT NULL, is_public TINYINT(1) NOT NULL, is_archived TINYINT(1) NOT NULL, status VARCHAR(50) NOT NULL, tenant_id INT DEFAULT NULL, uploaded_by_id INT NOT NULL, INDEX IDX_D8698A76A2B28FE8 (uploaded_by_id), INDEX idx_document_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE incident (id INT AUTO_INCREMENT NOT NULL, incident_number VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, category VARCHAR(100) NOT NULL, severity VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, detected_at DATETIME NOT NULL, occurred_at DATETIME DEFAULT NULL, reported_by VARCHAR(100) NOT NULL, assigned_to VARCHAR(100) DEFAULT NULL, affected_systems LONGTEXT DEFAULT NULL, immediate_actions LONGTEXT DEFAULT NULL, root_cause LONGTEXT DEFAULT NULL, corrective_actions LONGTEXT DEFAULT NULL, preventive_actions LONGTEXT DEFAULT NULL, lessons_learned LONGTEXT DEFAULT NULL, resolved_at DATETIME DEFAULT NULL, closed_at DATETIME DEFAULT NULL, data_breach_occurred TINYINT(1) NOT NULL, notification_required TINYINT(1) NOT NULL, early_warning_reported_at DATETIME DEFAULT NULL, detailed_notification_reported_at DATETIME DEFAULT NULL, final_report_submitted_at DATETIME DEFAULT NULL, nis2_category VARCHAR(50) DEFAULT NULL, cross_border_impact TINYINT(1) NOT NULL, affected_users_count INT DEFAULT NULL, estimated_financial_impact NUMERIC(12, 2) DEFAULT NULL, national_authority_notified VARCHAR(255) DEFAULT NULL, authority_reference_number VARCHAR(100) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, originating_threat_id INT DEFAULT NULL, INDEX IDX_3D03A11AF6FDF2B1 (originating_threat_id), INDEX idx_incident_number (incident_number), INDEX idx_incident_severity (severity), INDEX idx_incident_status (status), INDEX idx_incident_category (category), INDEX idx_incident_detected_at (detected_at), INDEX idx_incident_data_breach (data_breach_occurred), INDEX idx_incident_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE incident_control (incident_id INT NOT NULL, control_id INT NOT NULL, INDEX IDX_4A11369659E53FB9 (incident_id), INDEX IDX_4A11369632BEC70E (control_id), PRIMARY KEY (incident_id, control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE incident_asset (incident_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_599BF83659E53FB9 (incident_id), INDEX IDX_599BF8365DA1941 (asset_id), PRIMARY KEY (incident_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE incident_risk (incident_id INT NOT NULL, risk_id INT NOT NULL, INDEX IDX_930AA2FE59E53FB9 (incident_id), INDEX IDX_930AA2FE235B6D1 (risk_id), PRIMARY KEY (incident_id, risk_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE incident_failed_controls (incident_id INT NOT NULL, control_id INT NOT NULL, INDEX IDX_E592900E59E53FB9 (incident_id), INDEX IDX_E592900E32BEC70E (control_id), PRIMARY KEY (incident_id, control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE interested_party (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, party_type VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, contact_person VARCHAR(100) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, importance VARCHAR(50) NOT NULL, requirements LONGTEXT NOT NULL, legal_requirements JSON DEFAULT NULL, how_addressed LONGTEXT DEFAULT NULL, communication_frequency VARCHAR(100) DEFAULT NULL, communication_method LONGTEXT DEFAULT NULL, last_communication DATE DEFAULT NULL, next_communication DATE DEFAULT NULL, feedback LONGTEXT DEFAULT NULL, satisfaction_level INT DEFAULT NULL, issues LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX idx_party_type (party_type), INDEX idx_party_importance (importance), INDEX idx_interested_party_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE internal_audit (id INT AUTO_INCREMENT NOT NULL, audit_number VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, scope LONGTEXT DEFAULT NULL, scope_type VARCHAR(50) DEFAULT NULL, scope_details JSON DEFAULT NULL, objectives LONGTEXT DEFAULT NULL, planned_date DATE NOT NULL, actual_date DATE DEFAULT NULL, lead_auditor VARCHAR(100) NOT NULL, audit_team LONGTEXT DEFAULT NULL, audited_departments LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, findings LONGTEXT DEFAULT NULL, non_conformities LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, recommendations LONGTEXT DEFAULT NULL, conclusion LONGTEXT DEFAULT NULL, report_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, scoped_framework_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_9E4264D0E0953C03 (scoped_framework_id), INDEX IDX_9E4264D09033212A (tenant_id), INDEX idx_audit_number (audit_number), INDEX idx_audit_status (status), INDEX idx_audit_scope_type (scope_type), INDEX idx_audit_planned_date (planned_date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE internal_audit_asset (internal_audit_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_308B7E2E728B7E81 (internal_audit_id), INDEX IDX_308B7E2E5DA1941 (asset_id), PRIMARY KEY (internal_audit_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE ismscontext (id INT AUTO_INCREMENT NOT NULL, organization_name VARCHAR(255) NOT NULL, isms_scope LONGTEXT DEFAULT NULL, scope_exclusions LONGTEXT DEFAULT NULL, external_issues LONGTEXT DEFAULT NULL, internal_issues LONGTEXT DEFAULT NULL, interested_parties LONGTEXT DEFAULT NULL, interested_parties_requirements LONGTEXT DEFAULT NULL, legal_requirements LONGTEXT DEFAULT NULL, regulatory_requirements LONGTEXT DEFAULT NULL, contractual_obligations LONGTEXT DEFAULT NULL, isms_policy LONGTEXT DEFAULT NULL, roles_and_responsibilities LONGTEXT DEFAULT NULL, last_review_date DATE DEFAULT NULL, next_review_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_ADA28D4A9033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE ismsobjective (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, category VARCHAR(100) NOT NULL, measurable_indicators LONGTEXT DEFAULT NULL, target_value NUMERIC(10, 2) DEFAULT NULL, current_value NUMERIC(10, 2) DEFAULT NULL, unit VARCHAR(50) DEFAULT NULL, responsible_person VARCHAR(100) NOT NULL, target_date DATE NOT NULL, status VARCHAR(50) NOT NULL, progress_notes LONGTEXT DEFAULT NULL, achieved_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_C67C53B9033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, location_type VARCHAR(100) NOT NULL, code VARCHAR(50) DEFAULT NULL, description LONGTEXT DEFAULT NULL, address LONGTEXT DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, security_level VARCHAR(50) NOT NULL, requires_badge_access TINYINT(1) NOT NULL, requires_escort TINYINT(1) NOT NULL, camera_monitored TINYINT(1) NOT NULL, access_control_system VARCHAR(255) DEFAULT NULL, responsible_person VARCHAR(255) DEFAULT NULL, capacity INT DEFAULT NULL, square_meters NUMERIC(10, 2) DEFAULT NULL, active TINYINT(1) NOT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, parent_location_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_5E9E89CB6D6133FE (parent_location_id), INDEX IDX_5E9E89CB9033212A (tenant_id), INDEX idx_location_type (location_type), INDEX idx_location_active (active), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE management_review (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, review_date DATE NOT NULL, participants LONGTEXT DEFAULT NULL, changes_relevant_to_isms LONGTEXT DEFAULT NULL, feedback_from_interested_parties LONGTEXT DEFAULT NULL, audit_results LONGTEXT DEFAULT NULL, performance_evaluation LONGTEXT DEFAULT NULL, non_conformities_status LONGTEXT DEFAULT NULL, corrective_actions_status LONGTEXT DEFAULT NULL, previous_review_actions LONGTEXT DEFAULT NULL, opportunities_for_improvement LONGTEXT DEFAULT NULL, resource_needs LONGTEXT DEFAULT NULL, decisions LONGTEXT DEFAULT NULL, action_items LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_4F5A850C9033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE mfa_tokens (id INT AUTO_INCREMENT NOT NULL, token_type VARCHAR(20) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, secret LONGTEXT DEFAULT NULL, backup_codes JSON DEFAULT NULL, credential_id LONGTEXT DEFAULT NULL, public_key LONGTEXT DEFAULT NULL, counter INT DEFAULT NULL, phone_number VARCHAR(20) DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_primary TINYINT(1) NOT NULL, last_used_at DATETIME DEFAULT NULL, usage_count INT NOT NULL, enrolled_at DATETIME NOT NULL, expires_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX idx_mfa_user (user_id), INDEX idx_mfa_type (token_type), INDEX idx_mfa_active (is_active), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE patches (id INT AUTO_INCREMENT NOT NULL, patch_id VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, vendor VARCHAR(100) NOT NULL, product VARCHAR(255) NOT NULL, version VARCHAR(50) DEFAULT NULL, patch_type VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, release_date DATE NOT NULL, deployment_deadline DATE DEFAULT NULL, deployed_date DATE DEFAULT NULL, responsible_person VARCHAR(100) DEFAULT NULL, testing_notes LONGTEXT DEFAULT NULL, deployment_notes LONGTEXT DEFAULT NULL, rollback_plan LONGTEXT DEFAULT NULL, requires_downtime TINYINT(1) NOT NULL, estimated_downtime_minutes INT DEFAULT NULL, requires_reboot TINYINT(1) NOT NULL, known_issues LONGTEXT DEFAULT NULL, dependencies JSON DEFAULT NULL, download_url LONGTEXT DEFAULT NULL, documentation_url LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, vulnerability_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_2FE8B472897D8B (vulnerability_id), INDEX IDX_2FE8B49033212A (tenant_id), INDEX idx_patch_id (patch_id), INDEX idx_patch_status (status), INDEX idx_patch_release (release_date), INDEX idx_patch_deadline (deployment_deadline), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE patch_asset (patch_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_D9A7AC31CD00882C (patch_id), INDEX IDX_D9A7AC315DA1941 (asset_id), PRIMARY KEY (patch_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE permissions (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, category VARCHAR(50) NOT NULL, action VARCHAR(50) NOT NULL, is_system_permission TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_2DEDCC6F5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, full_name VARCHAR(255) NOT NULL, person_type VARCHAR(50) NOT NULL, badge_id VARCHAR(100) DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, department VARCHAR(100) DEFAULT NULL, job_title VARCHAR(100) DEFAULT NULL, active TINYINT(1) NOT NULL, notes LONGTEXT DEFAULT NULL, access_valid_from DATE DEFAULT NULL, access_valid_until DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, linked_user_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_34DCD176F7A2C2FC (badge_id), INDEX IDX_34DCD176CC26EB02 (linked_user_id), INDEX IDX_34DCD1769033212A (tenant_id), INDEX idx_person_type (person_type), INDEX idx_person_badge (badge_id), INDEX idx_person_company (company), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE physical_access_log (id INT AUTO_INCREMENT NOT NULL, person_name VARCHAR(255) DEFAULT NULL, badge_id VARCHAR(100) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, access_type VARCHAR(50) NOT NULL, access_time DATETIME NOT NULL, authentication_method VARCHAR(50) NOT NULL, purpose VARCHAR(100) DEFAULT NULL, escorted_by VARCHAR(255) DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, authorized TINYINT(1) NOT NULL, notes LONGTEXT DEFAULT NULL, alert_level VARCHAR(50) DEFAULT NULL, after_hours TINYINT(1) NOT NULL, door_or_gate VARCHAR(255) DEFAULT NULL, exit_time DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, person_id INT DEFAULT NULL, location_entity_id INT DEFAULT NULL, user_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_7C8EEDE8217BBB47 (person_id), INDEX IDX_7C8EEDE8CFF0AB2B (location_entity_id), INDEX IDX_7C8EEDE8A76ED395 (user_id), INDEX IDX_7C8EEDE89033212A (tenant_id), INDEX idx_physical_access_time (access_time), INDEX idx_physical_access_type (access_type), INDEX idx_physical_location (location), INDEX idx_physical_person (person_name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE risk (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, threat LONGTEXT DEFAULT NULL, vulnerability LONGTEXT DEFAULT NULL, probability INT NOT NULL, impact INT NOT NULL, residual_probability INT NOT NULL, residual_impact INT NOT NULL, treatment_strategy VARCHAR(50) NOT NULL, treatment_description LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, review_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, acceptance_approved_by VARCHAR(100) DEFAULT NULL, acceptance_approved_at DATE DEFAULT NULL, acceptance_justification LONGTEXT DEFAULT NULL, formally_accepted TINYINT(1) NOT NULL, tenant_id INT DEFAULT NULL, asset_id INT DEFAULT NULL, risk_owner_id INT DEFAULT NULL, INDEX IDX_7906D5415DA1941 (asset_id), INDEX IDX_7906D54198152296 (risk_owner_id), INDEX idx_risk_status (status), INDEX idx_risk_created_at (created_at), INDEX idx_risk_review_date (review_date), INDEX idx_risk_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE risk_appetite (id INT AUTO_INCREMENT NOT NULL, category VARCHAR(100) DEFAULT NULL, max_acceptable_risk INT NOT NULL, description LONGTEXT NOT NULL, is_active TINYINT(1) NOT NULL, approved_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, INDEX IDX_FC02F7B52D234F6A (approved_by_id), INDEX idx_risk_appetite_category (category), INDEX idx_risk_appetite_active (is_active), INDEX idx_risk_appetite_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE risk_treatment_plan (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(20) NOT NULL, start_date DATE DEFAULT NULL, target_completion_date DATE NOT NULL, actual_completion_date DATE DEFAULT NULL, budget NUMERIC(15, 2) DEFAULT NULL, implementation_notes LONGTEXT DEFAULT NULL, completion_percentage INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, risk_id INT NOT NULL, responsible_person_id INT DEFAULT NULL, INDEX IDX_883D44DC235B6D1 (risk_id), INDEX IDX_883D44DCEF64F467 (responsible_person_id), INDEX idx_treatment_plan_status (status), INDEX idx_treatment_plan_priority (priority), INDEX idx_treatment_plan_target (target_completion_date), INDEX idx_treatment_plan_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE risk_treatment_plan_control (risk_treatment_plan_id INT NOT NULL, control_id INT NOT NULL, INDEX IDX_4117102F2EAFCFFC (risk_treatment_plan_id), INDEX IDX_4117102F32BEC70E (control_id), PRIMARY KEY (risk_treatment_plan_id, control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE roles (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, is_system_role TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B63E2EC75E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, INDEX IDX_1FBA94E6D60322AC (role_id), INDEX IDX_1FBA94E6FED90CCA (permission_id), PRIMARY KEY (role_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE supplier (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, contact_person VARCHAR(100) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address LONGTEXT DEFAULT NULL, service_provided LONGTEXT NOT NULL, criticality VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, security_score INT DEFAULT NULL, last_security_assessment DATE DEFAULT NULL, next_assessment_date DATE DEFAULT NULL, assessment_findings LONGTEXT DEFAULT NULL, non_conformities LONGTEXT DEFAULT NULL, contractual_slas JSON DEFAULT NULL, contract_start_date DATE DEFAULT NULL, contract_end_date DATE DEFAULT NULL, security_requirements LONGTEXT DEFAULT NULL, has_iso27001 TINYINT(1) NOT NULL, has_iso22301 TINYINT(1) NOT NULL, certifications LONGTEXT DEFAULT NULL, has_dpa TINYINT(1) NOT NULL, dpa_signed_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX idx_supplier_criticality (criticality), INDEX idx_supplier_next_assessment (next_assessment_date), INDEX idx_supplier_status (status), INDEX idx_supplier_tenant (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE supplier_asset (supplier_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_DBB458762ADD6D8C (supplier_id), INDEX IDX_DBB458765DA1941 (asset_id), PRIMARY KEY (supplier_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE supplier_risk (supplier_id INT NOT NULL, risk_id INT NOT NULL, INDEX IDX_B45E23A82ADD6D8C (supplier_id), INDEX IDX_B45E23A8235B6D1 (risk_id), PRIMARY KEY (supplier_id, risk_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE supplier_document (supplier_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_55E0E2F72ADD6D8C (supplier_id), INDEX IDX_55E0E2F7C33F7837 (document_id), PRIMARY KEY (supplier_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE system_settings (id INT AUTO_INCREMENT NOT NULL, category VARCHAR(50) NOT NULL, setting_key VARCHAR(100) NOT NULL, value JSON NOT NULL, encrypted_value LONGTEXT DEFAULT NULL, is_encrypted TINYINT(1) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, UNIQUE INDEX UNIQ_CATEGORY_KEY (category, setting_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE tenant (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, azure_tenant_id VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, settings JSON DEFAULT NULL, logo_path VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4E59C46277153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE threat_intelligence (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, threat_type VARCHAR(100) NOT NULL, severity VARCHAR(50) NOT NULL, source VARCHAR(255) DEFAULT NULL, cve_id VARCHAR(255) DEFAULT NULL, affected_systems JSON DEFAULT NULL, indicators JSON DEFAULT NULL, mitigation_recommendations LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, detection_date DATE NOT NULL, mitigation_date DATE DEFAULT NULL, actions_taken LONGTEXT DEFAULT NULL, affects_organization TINYINT(1) NOT NULL, cvss_score INT DEFAULT NULL, `references` LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, assigned_to_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_C2556D7FF4BD7827 (assigned_to_id), INDEX IDX_C2556D7F9033212A (tenant_id), INDEX idx_threat_type (threat_type), INDEX idx_threat_severity (severity), INDEX idx_threat_status (status), INDEX idx_threat_detection_date (detection_date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE threat_intelligence_affected_assets (threat_intelligence_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_63D51DCDF2BE5A0E (threat_intelligence_id), INDEX IDX_63D51DCD5DA1941 (asset_id), PRIMARY KEY (threat_intelligence_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE training (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, training_type VARCHAR(100) NOT NULL, scheduled_date DATE NOT NULL, duration_minutes INT DEFAULT NULL, trainer VARCHAR(100) NOT NULL, target_audience LONGTEXT DEFAULT NULL, participants LONGTEXT DEFAULT NULL, attendee_count INT DEFAULT NULL, status VARCHAR(50) NOT NULL, materials LONGTEXT DEFAULT NULL, feedback LONGTEXT DEFAULT NULL, completion_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_D5128A8F9033212A (tenant_id), INDEX idx_training_type (training_type), INDEX idx_training_status (status), INDEX idx_training_scheduled_date (scheduled_date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE training_control (training_id INT NOT NULL, control_id INT NOT NULL, INDEX IDX_30E5BC45BEFD98D1 (training_id), INDEX IDX_30E5BC4532BEC70E (control_id), PRIMARY KEY (training_id, control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE training_compliance_requirement (training_id INT NOT NULL, compliance_requirement_id INT NOT NULL, INDEX IDX_E62BC234BEFD98D1 (training_id), INDEX IDX_E62BC234492951C7 (compliance_requirement_id), PRIMARY KEY (training_id, compliance_requirement_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_active TINYINT(1) NOT NULL, is_verified TINYINT(1) NOT NULL, auth_provider VARCHAR(20) DEFAULT NULL, azure_object_id VARCHAR(255) DEFAULT NULL, azure_tenant_id VARCHAR(255) DEFAULT NULL, azure_metadata JSON DEFAULT NULL, created_at DATETIME NOT NULL, last_login_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, department VARCHAR(255) DEFAULT NULL, job_title VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(50) DEFAULT NULL, profile_picture LONGTEXT DEFAULT NULL, language VARCHAR(10) DEFAULT NULL, timezone VARCHAR(50) DEFAULT NULL, tenant_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9D75C81F4 (azure_object_id), INDEX IDX_1483A5E99033212A (tenant_id), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_roles (user_id INT NOT NULL, role_id INT NOT NULL, INDEX IDX_54FCD59FA76ED395 (user_id), INDEX IDX_54FCD59FD60322AC (role_id), PRIMARY KEY (user_id, role_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE vulnerabilities (id INT AUTO_INCREMENT NOT NULL, cve_id VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, severity VARCHAR(20) NOT NULL, cvss_score NUMERIC(3, 1) NOT NULL, cvss_vector LONGTEXT DEFAULT NULL, source VARCHAR(50) NOT NULL, status VARCHAR(30) NOT NULL, discovered_date DATE NOT NULL, published_date DATE DEFAULT NULL, remediation_deadline DATE DEFAULT NULL, remediated_date DATE DEFAULT NULL, responsible_person VARCHAR(100) DEFAULT NULL, remediation_notes LONGTEXT DEFAULT NULL, exploit_availability VARCHAR(20) DEFAULT NULL, actively_exploited TINYINT(1) NOT NULL, `references` JSON DEFAULT NULL, cwe_ids JSON DEFAULT NULL, affected_products JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_459DFAF7DCC8D22B (cve_id), INDEX IDX_459DFAF79033212A (tenant_id), INDEX idx_vuln_cve (cve_id), INDEX idx_vuln_severity (severity), INDEX idx_vuln_status (status), INDEX idx_vuln_discovered (discovered_date), INDEX idx_vuln_deadline (remediation_deadline), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE vulnerability_asset (vulnerability_id INT NOT NULL, asset_id INT NOT NULL, INDEX IDX_F83FC91772897D8B (vulnerability_id), INDEX IDX_F83FC9175DA1941 (asset_id), PRIMARY KEY (vulnerability_id, asset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE workflow_instances (id INT AUTO_INCREMENT NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id INT NOT NULL, status VARCHAR(50) NOT NULL, completed_steps JSON DEFAULT NULL, approval_history JSON DEFAULT NULL, comments LONGTEXT DEFAULT NULL, started_at DATETIME NOT NULL, completed_at DATETIME DEFAULT NULL, due_date DATETIME DEFAULT NULL, workflow_id INT NOT NULL, initiated_by_id INT DEFAULT NULL, current_step_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_878E9AEC2C7C2CBA (workflow_id), INDEX IDX_878E9AECC4EF1FC7 (initiated_by_id), INDEX IDX_878E9AECD9BF9B19 (current_step_id), INDEX IDX_878E9AEC9033212A (tenant_id), INDEX IDX_878E9AECC412EE0281257D5D (entity_type, entity_id), INDEX IDX_878E9AEC7B00651C (status), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE workflow_steps (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, step_order INT NOT NULL, step_type VARCHAR(50) NOT NULL, approver_role VARCHAR(100) NOT NULL, approver_users JSON DEFAULT NULL, is_required TINYINT(1) NOT NULL, days_to_complete INT DEFAULT NULL, workflow_id INT NOT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_856C7C462C7C2CBA (workflow_id), INDEX IDX_856C7C469033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE workflows (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, entity_type VARCHAR(100) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, tenant_id INT DEFAULT NULL, INDEX IDX_EFBFBFC29033212A (tenant_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CB5B8AA78 FOREIGN KEY (physical_location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE audit_checklist ADD CONSTRAINT FK_85EF23A0BD29F359 FOREIGN KEY (audit_id) REFERENCES internal_audit (id)');
        $this->addSql('ALTER TABLE audit_checklist ADD CONSTRAINT FK_85EF23A07B576F77 FOREIGN KEY (requirement_id) REFERENCES compliance_requirement (id)');
        $this->addSql('ALTER TABLE audit_checklist ADD CONSTRAINT FK_85EF23A09033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE bc_exercise ADD CONSTRAINT FK_3FFCA5B49033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE bc_exercise_plan ADD CONSTRAINT FK_FB8DCC0DBCA4B399 FOREIGN KEY (bcexercise_id) REFERENCES bc_exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_exercise_plan ADD CONSTRAINT FK_FB8DCC0DE338D05C FOREIGN KEY (business_continuity_plan_id) REFERENCES business_continuity_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_exercise_document ADD CONSTRAINT FK_577E52BABCA4B399 FOREIGN KEY (bcexercise_id) REFERENCES bc_exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_exercise_document ADD CONSTRAINT FK_577E52BAC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE business_continuity_plan ADD CONSTRAINT FK_BC771CE69033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE business_continuity_plan ADD CONSTRAINT FK_BC771CE6BE61FDDF FOREIGN KEY (business_process_id) REFERENCES business_process (id)');
        $this->addSql('ALTER TABLE bc_plan_supplier ADD CONSTRAINT FK_EABDAEC6E338D05C FOREIGN KEY (business_continuity_plan_id) REFERENCES business_continuity_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_plan_supplier ADD CONSTRAINT FK_EABDAEC62ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_plan_asset ADD CONSTRAINT FK_67D2C95BE338D05C FOREIGN KEY (business_continuity_plan_id) REFERENCES business_continuity_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_plan_asset ADD CONSTRAINT FK_67D2C95B5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_plan_document ADD CONSTRAINT FK_A9FE48CEE338D05C FOREIGN KEY (business_continuity_plan_id) REFERENCES business_continuity_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bc_plan_document ADD CONSTRAINT FK_A9FE48CEC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE business_process ADD CONSTRAINT FK_DB2EA3DB9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE business_process_asset ADD CONSTRAINT FK_6D8BDB6BE61FDDF FOREIGN KEY (business_process_id) REFERENCES business_process (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE business_process_asset ADD CONSTRAINT FK_6D8BDB65DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE business_process_risk ADD CONSTRAINT FK_D5C72AC7BE61FDDF FOREIGN KEY (business_process_id) REFERENCES business_process (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE business_process_risk ADD CONSTRAINT FK_D5C72AC7235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request ADD CONSTRAINT FK_CB902D369033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE change_request_asset ADD CONSTRAINT FK_435F21C096829572 FOREIGN KEY (change_request_id) REFERENCES change_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_asset ADD CONSTRAINT FK_435F21C05DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_control ADD CONSTRAINT FK_F7F8001996829572 FOREIGN KEY (change_request_id) REFERENCES change_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_control ADD CONSTRAINT FK_F7F8001932BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_business_process ADD CONSTRAINT FK_754BBFCE96829572 FOREIGN KEY (change_request_id) REFERENCES change_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_business_process ADD CONSTRAINT FK_754BBFCEBE61FDDF FOREIGN KEY (business_process_id) REFERENCES business_process (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_risk ADD CONSTRAINT FK_8D0729EA96829572 FOREIGN KEY (change_request_id) REFERENCES change_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_risk ADD CONSTRAINT FK_8D0729EA235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_document ADD CONSTRAINT FK_5D16998296829572 FOREIGN KEY (change_request_id) REFERENCES change_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_request_document ADD CONSTRAINT FK_5D169982C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE compliance_mapping ADD CONSTRAINT FK_3D5913BD82E03D2 FOREIGN KEY (source_requirement_id) REFERENCES compliance_requirement (id)');
        $this->addSql('ALTER TABLE compliance_mapping ADD CONSTRAINT FK_3D5913BC72D605E FOREIGN KEY (target_requirement_id) REFERENCES compliance_requirement (id)');
        $this->addSql('ALTER TABLE compliance_requirement ADD CONSTRAINT FK_D115DC5237AECF72 FOREIGN KEY (framework_id) REFERENCES compliance_framework (id)');
        $this->addSql('ALTER TABLE compliance_requirement ADD CONSTRAINT FK_D115DC52658A1B7C FOREIGN KEY (parent_requirement_id) REFERENCES compliance_requirement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE compliance_requirement_control ADD CONSTRAINT FK_57D957D492951C7 FOREIGN KEY (compliance_requirement_id) REFERENCES compliance_requirement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE compliance_requirement_control ADD CONSTRAINT FK_57D957D32BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE control ADD CONSTRAINT FK_EDDB2C4B9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE control_risk ADD CONSTRAINT FK_8BE88BF432BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE control_risk ADD CONSTRAINT FK_8BE88BF4235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE control_asset ADD CONSTRAINT FK_B956F30132BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE control_asset ADD CONSTRAINT FK_B956F3015DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE crisis_teams ADD CONSTRAINT FK_D9975D4EC4105033 FOREIGN KEY (team_leader_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE crisis_teams ADD CONSTRAINT FK_D9975D4E42E65CAD FOREIGN KEY (deputy_leader_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE crisis_teams ADD CONSTRAINT FK_D9975D4E9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE crisis_team_bcp ADD CONSTRAINT FK_5B591A6FF54E4E81 FOREIGN KEY (crisis_team_id) REFERENCES crisis_teams (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE crisis_team_bcp ADD CONSTRAINT FK_5B591A6FE338D05C FOREIGN KEY (business_continuity_plan_id) REFERENCES business_continuity_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cryptographic_operation ADD CONSTRAINT FK_9E980109A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE cryptographic_operation ADD CONSTRAINT FK_9E980109A35957EC FOREIGN KEY (related_asset_id) REFERENCES asset (id)');
        $this->addSql('ALTER TABLE cryptographic_operation ADD CONSTRAINT FK_9E9801099033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A769033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11AF6FDF2B1 FOREIGN KEY (originating_threat_id) REFERENCES threat_intelligence (id)');
        $this->addSql('ALTER TABLE incident_control ADD CONSTRAINT FK_4A11369659E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_control ADD CONSTRAINT FK_4A11369632BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_asset ADD CONSTRAINT FK_599BF83659E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_asset ADD CONSTRAINT FK_599BF8365DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_risk ADD CONSTRAINT FK_930AA2FE59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_risk ADD CONSTRAINT FK_930AA2FE235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_failed_controls ADD CONSTRAINT FK_E592900E59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_failed_controls ADD CONSTRAINT FK_E592900E32BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interested_party ADD CONSTRAINT FK_4B8D8C2C9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE internal_audit ADD CONSTRAINT FK_9E4264D0E0953C03 FOREIGN KEY (scoped_framework_id) REFERENCES compliance_framework (id)');
        $this->addSql('ALTER TABLE internal_audit ADD CONSTRAINT FK_9E4264D09033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE internal_audit_asset ADD CONSTRAINT FK_308B7E2E728B7E81 FOREIGN KEY (internal_audit_id) REFERENCES internal_audit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE internal_audit_asset ADD CONSTRAINT FK_308B7E2E5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ismscontext ADD CONSTRAINT FK_ADA28D4A9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE ismsobjective ADD CONSTRAINT FK_C67C53B9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB6D6133FE FOREIGN KEY (parent_location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE management_review ADD CONSTRAINT FK_4F5A850C9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE mfa_tokens ADD CONSTRAINT FK_3AAE96CEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE patches ADD CONSTRAINT FK_2FE8B472897D8B FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE patches ADD CONSTRAINT FK_2FE8B49033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE patch_asset ADD CONSTRAINT FK_D9A7AC31CD00882C FOREIGN KEY (patch_id) REFERENCES patches (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE patch_asset ADD CONSTRAINT FK_D9A7AC315DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176CC26EB02 FOREIGN KEY (linked_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1769033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE physical_access_log ADD CONSTRAINT FK_7C8EEDE8217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE physical_access_log ADD CONSTRAINT FK_7C8EEDE8CFF0AB2B FOREIGN KEY (location_entity_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE physical_access_log ADD CONSTRAINT FK_7C8EEDE8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE physical_access_log ADD CONSTRAINT FK_7C8EEDE89033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D5419033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D5415DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D54198152296 FOREIGN KEY (risk_owner_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk_appetite ADD CONSTRAINT FK_FC02F7B59033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE risk_appetite ADD CONSTRAINT FK_FC02F7B52D234F6A FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk_treatment_plan ADD CONSTRAINT FK_883D44DC9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE risk_treatment_plan ADD CONSTRAINT FK_883D44DC235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_treatment_plan ADD CONSTRAINT FK_883D44DCEF64F467 FOREIGN KEY (responsible_person_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk_treatment_plan_control ADD CONSTRAINT FK_4117102F2EAFCFFC FOREIGN KEY (risk_treatment_plan_id) REFERENCES risk_treatment_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_treatment_plan_control ADD CONSTRAINT FK_4117102F32BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE supplier_asset ADD CONSTRAINT FK_DBB458762ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_asset ADD CONSTRAINT FK_DBB458765DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_risk ADD CONSTRAINT FK_B45E23A82ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_risk ADD CONSTRAINT FK_B45E23A8235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_document ADD CONSTRAINT FK_55E0E2F72ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_document ADD CONSTRAINT FK_55E0E2F7C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE threat_intelligence ADD CONSTRAINT FK_C2556D7FF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE threat_intelligence ADD CONSTRAINT FK_C2556D7F9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE threat_intelligence_affected_assets ADD CONSTRAINT FK_63D51DCDF2BE5A0E FOREIGN KEY (threat_intelligence_id) REFERENCES threat_intelligence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE threat_intelligence_affected_assets ADD CONSTRAINT FK_63D51DCD5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8F9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE training_control ADD CONSTRAINT FK_30E5BC45BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE training_control ADD CONSTRAINT FK_30E5BC4532BEC70E FOREIGN KEY (control_id) REFERENCES control (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE training_compliance_requirement ADD CONSTRAINT FK_E62BC234BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE training_compliance_requirement ADD CONSTRAINT FK_E62BC234492951C7 FOREIGN KEY (compliance_requirement_id) REFERENCES compliance_requirement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E99033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vulnerabilities ADD CONSTRAINT FK_459DFAF79033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE vulnerability_asset ADD CONSTRAINT FK_F83FC91772897D8B FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vulnerability_asset ADD CONSTRAINT FK_F83FC9175DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workflow_instances ADD CONSTRAINT FK_878E9AEC2C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflows (id)');
        $this->addSql('ALTER TABLE workflow_instances ADD CONSTRAINT FK_878E9AECC4EF1FC7 FOREIGN KEY (initiated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE workflow_instances ADD CONSTRAINT FK_878E9AECD9BF9B19 FOREIGN KEY (current_step_id) REFERENCES workflow_steps (id)');
        $this->addSql('ALTER TABLE workflow_instances ADD CONSTRAINT FK_878E9AEC9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE workflow_steps ADD CONSTRAINT FK_856C7C462C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflows (id)');
        $this->addSql('ALTER TABLE workflow_steps ADD CONSTRAINT FK_856C7C469033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE workflows ADD CONSTRAINT FK_EFBFBFC29033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5C9033212A');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5CB5B8AA78');
        $this->addSql('ALTER TABLE audit_checklist DROP FOREIGN KEY FK_85EF23A0BD29F359');
        $this->addSql('ALTER TABLE audit_checklist DROP FOREIGN KEY FK_85EF23A07B576F77');
        $this->addSql('ALTER TABLE audit_checklist DROP FOREIGN KEY FK_85EF23A09033212A');
        $this->addSql('ALTER TABLE bc_exercise DROP FOREIGN KEY FK_3FFCA5B49033212A');
        $this->addSql('ALTER TABLE bc_exercise_plan DROP FOREIGN KEY FK_FB8DCC0DBCA4B399');
        $this->addSql('ALTER TABLE bc_exercise_plan DROP FOREIGN KEY FK_FB8DCC0DE338D05C');
        $this->addSql('ALTER TABLE bc_exercise_document DROP FOREIGN KEY FK_577E52BABCA4B399');
        $this->addSql('ALTER TABLE bc_exercise_document DROP FOREIGN KEY FK_577E52BAC33F7837');
        $this->addSql('ALTER TABLE business_continuity_plan DROP FOREIGN KEY FK_BC771CE69033212A');
        $this->addSql('ALTER TABLE business_continuity_plan DROP FOREIGN KEY FK_BC771CE6BE61FDDF');
        $this->addSql('ALTER TABLE bc_plan_supplier DROP FOREIGN KEY FK_EABDAEC6E338D05C');
        $this->addSql('ALTER TABLE bc_plan_supplier DROP FOREIGN KEY FK_EABDAEC62ADD6D8C');
        $this->addSql('ALTER TABLE bc_plan_asset DROP FOREIGN KEY FK_67D2C95BE338D05C');
        $this->addSql('ALTER TABLE bc_plan_asset DROP FOREIGN KEY FK_67D2C95B5DA1941');
        $this->addSql('ALTER TABLE bc_plan_document DROP FOREIGN KEY FK_A9FE48CEE338D05C');
        $this->addSql('ALTER TABLE bc_plan_document DROP FOREIGN KEY FK_A9FE48CEC33F7837');
        $this->addSql('ALTER TABLE business_process DROP FOREIGN KEY FK_DB2EA3DB9033212A');
        $this->addSql('ALTER TABLE business_process_asset DROP FOREIGN KEY FK_6D8BDB6BE61FDDF');
        $this->addSql('ALTER TABLE business_process_asset DROP FOREIGN KEY FK_6D8BDB65DA1941');
        $this->addSql('ALTER TABLE business_process_risk DROP FOREIGN KEY FK_D5C72AC7BE61FDDF');
        $this->addSql('ALTER TABLE business_process_risk DROP FOREIGN KEY FK_D5C72AC7235B6D1');
        $this->addSql('ALTER TABLE change_request DROP FOREIGN KEY FK_CB902D369033212A');
        $this->addSql('ALTER TABLE change_request_asset DROP FOREIGN KEY FK_435F21C096829572');
        $this->addSql('ALTER TABLE change_request_asset DROP FOREIGN KEY FK_435F21C05DA1941');
        $this->addSql('ALTER TABLE change_request_control DROP FOREIGN KEY FK_F7F8001996829572');
        $this->addSql('ALTER TABLE change_request_control DROP FOREIGN KEY FK_F7F8001932BEC70E');
        $this->addSql('ALTER TABLE change_request_business_process DROP FOREIGN KEY FK_754BBFCE96829572');
        $this->addSql('ALTER TABLE change_request_business_process DROP FOREIGN KEY FK_754BBFCEBE61FDDF');
        $this->addSql('ALTER TABLE change_request_risk DROP FOREIGN KEY FK_8D0729EA96829572');
        $this->addSql('ALTER TABLE change_request_risk DROP FOREIGN KEY FK_8D0729EA235B6D1');
        $this->addSql('ALTER TABLE change_request_document DROP FOREIGN KEY FK_5D16998296829572');
        $this->addSql('ALTER TABLE change_request_document DROP FOREIGN KEY FK_5D169982C33F7837');
        $this->addSql('ALTER TABLE compliance_mapping DROP FOREIGN KEY FK_3D5913BD82E03D2');
        $this->addSql('ALTER TABLE compliance_mapping DROP FOREIGN KEY FK_3D5913BC72D605E');
        $this->addSql('ALTER TABLE compliance_requirement DROP FOREIGN KEY FK_D115DC5237AECF72');
        $this->addSql('ALTER TABLE compliance_requirement DROP FOREIGN KEY FK_D115DC52658A1B7C');
        $this->addSql('ALTER TABLE compliance_requirement_control DROP FOREIGN KEY FK_57D957D492951C7');
        $this->addSql('ALTER TABLE compliance_requirement_control DROP FOREIGN KEY FK_57D957D32BEC70E');
        $this->addSql('ALTER TABLE control DROP FOREIGN KEY FK_EDDB2C4B9033212A');
        $this->addSql('ALTER TABLE control_risk DROP FOREIGN KEY FK_8BE88BF432BEC70E');
        $this->addSql('ALTER TABLE control_risk DROP FOREIGN KEY FK_8BE88BF4235B6D1');
        $this->addSql('ALTER TABLE control_asset DROP FOREIGN KEY FK_B956F30132BEC70E');
        $this->addSql('ALTER TABLE control_asset DROP FOREIGN KEY FK_B956F3015DA1941');
        $this->addSql('ALTER TABLE crisis_teams DROP FOREIGN KEY FK_D9975D4EC4105033');
        $this->addSql('ALTER TABLE crisis_teams DROP FOREIGN KEY FK_D9975D4E42E65CAD');
        $this->addSql('ALTER TABLE crisis_teams DROP FOREIGN KEY FK_D9975D4E9033212A');
        $this->addSql('ALTER TABLE crisis_team_bcp DROP FOREIGN KEY FK_5B591A6FF54E4E81');
        $this->addSql('ALTER TABLE crisis_team_bcp DROP FOREIGN KEY FK_5B591A6FE338D05C');
        $this->addSql('ALTER TABLE cryptographic_operation DROP FOREIGN KEY FK_9E980109A76ED395');
        $this->addSql('ALTER TABLE cryptographic_operation DROP FOREIGN KEY FK_9E980109A35957EC');
        $this->addSql('ALTER TABLE cryptographic_operation DROP FOREIGN KEY FK_9E9801099033212A');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A769033212A');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76A2B28FE8');
        $this->addSql('ALTER TABLE incident DROP FOREIGN KEY FK_3D03A11A9033212A');
        $this->addSql('ALTER TABLE incident DROP FOREIGN KEY FK_3D03A11AF6FDF2B1');
        $this->addSql('ALTER TABLE incident_control DROP FOREIGN KEY FK_4A11369659E53FB9');
        $this->addSql('ALTER TABLE incident_control DROP FOREIGN KEY FK_4A11369632BEC70E');
        $this->addSql('ALTER TABLE incident_asset DROP FOREIGN KEY FK_599BF83659E53FB9');
        $this->addSql('ALTER TABLE incident_asset DROP FOREIGN KEY FK_599BF8365DA1941');
        $this->addSql('ALTER TABLE incident_risk DROP FOREIGN KEY FK_930AA2FE59E53FB9');
        $this->addSql('ALTER TABLE incident_risk DROP FOREIGN KEY FK_930AA2FE235B6D1');
        $this->addSql('ALTER TABLE incident_failed_controls DROP FOREIGN KEY FK_E592900E59E53FB9');
        $this->addSql('ALTER TABLE incident_failed_controls DROP FOREIGN KEY FK_E592900E32BEC70E');
        $this->addSql('ALTER TABLE interested_party DROP FOREIGN KEY FK_4B8D8C2C9033212A');
        $this->addSql('ALTER TABLE internal_audit DROP FOREIGN KEY FK_9E4264D0E0953C03');
        $this->addSql('ALTER TABLE internal_audit DROP FOREIGN KEY FK_9E4264D09033212A');
        $this->addSql('ALTER TABLE internal_audit_asset DROP FOREIGN KEY FK_308B7E2E728B7E81');
        $this->addSql('ALTER TABLE internal_audit_asset DROP FOREIGN KEY FK_308B7E2E5DA1941');
        $this->addSql('ALTER TABLE ismscontext DROP FOREIGN KEY FK_ADA28D4A9033212A');
        $this->addSql('ALTER TABLE ismsobjective DROP FOREIGN KEY FK_C67C53B9033212A');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB6D6133FE');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB9033212A');
        $this->addSql('ALTER TABLE management_review DROP FOREIGN KEY FK_4F5A850C9033212A');
        $this->addSql('ALTER TABLE mfa_tokens DROP FOREIGN KEY FK_3AAE96CEA76ED395');
        $this->addSql('ALTER TABLE patches DROP FOREIGN KEY FK_2FE8B472897D8B');
        $this->addSql('ALTER TABLE patches DROP FOREIGN KEY FK_2FE8B49033212A');
        $this->addSql('ALTER TABLE patch_asset DROP FOREIGN KEY FK_D9A7AC31CD00882C');
        $this->addSql('ALTER TABLE patch_asset DROP FOREIGN KEY FK_D9A7AC315DA1941');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176CC26EB02');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD1769033212A');
        $this->addSql('ALTER TABLE physical_access_log DROP FOREIGN KEY FK_7C8EEDE8217BBB47');
        $this->addSql('ALTER TABLE physical_access_log DROP FOREIGN KEY FK_7C8EEDE8CFF0AB2B');
        $this->addSql('ALTER TABLE physical_access_log DROP FOREIGN KEY FK_7C8EEDE8A76ED395');
        $this->addSql('ALTER TABLE physical_access_log DROP FOREIGN KEY FK_7C8EEDE89033212A');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D5419033212A');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D5415DA1941');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D54198152296');
        $this->addSql('ALTER TABLE risk_appetite DROP FOREIGN KEY FK_FC02F7B59033212A');
        $this->addSql('ALTER TABLE risk_appetite DROP FOREIGN KEY FK_FC02F7B52D234F6A');
        $this->addSql('ALTER TABLE risk_treatment_plan DROP FOREIGN KEY FK_883D44DC9033212A');
        $this->addSql('ALTER TABLE risk_treatment_plan DROP FOREIGN KEY FK_883D44DC235B6D1');
        $this->addSql('ALTER TABLE risk_treatment_plan DROP FOREIGN KEY FK_883D44DCEF64F467');
        $this->addSql('ALTER TABLE risk_treatment_plan_control DROP FOREIGN KEY FK_4117102F2EAFCFFC');
        $this->addSql('ALTER TABLE risk_treatment_plan_control DROP FOREIGN KEY FK_4117102F32BEC70E');
        $this->addSql('ALTER TABLE role_permissions DROP FOREIGN KEY FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE role_permissions DROP FOREIGN KEY FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE supplier DROP FOREIGN KEY FK_9B2A6C7E9033212A');
        $this->addSql('ALTER TABLE supplier_asset DROP FOREIGN KEY FK_DBB458762ADD6D8C');
        $this->addSql('ALTER TABLE supplier_asset DROP FOREIGN KEY FK_DBB458765DA1941');
        $this->addSql('ALTER TABLE supplier_risk DROP FOREIGN KEY FK_B45E23A82ADD6D8C');
        $this->addSql('ALTER TABLE supplier_risk DROP FOREIGN KEY FK_B45E23A8235B6D1');
        $this->addSql('ALTER TABLE supplier_document DROP FOREIGN KEY FK_55E0E2F72ADD6D8C');
        $this->addSql('ALTER TABLE supplier_document DROP FOREIGN KEY FK_55E0E2F7C33F7837');
        $this->addSql('ALTER TABLE threat_intelligence DROP FOREIGN KEY FK_C2556D7FF4BD7827');
        $this->addSql('ALTER TABLE threat_intelligence DROP FOREIGN KEY FK_C2556D7F9033212A');
        $this->addSql('ALTER TABLE threat_intelligence_affected_assets DROP FOREIGN KEY FK_63D51DCDF2BE5A0E');
        $this->addSql('ALTER TABLE threat_intelligence_affected_assets DROP FOREIGN KEY FK_63D51DCD5DA1941');
        $this->addSql('ALTER TABLE training DROP FOREIGN KEY FK_D5128A8F9033212A');
        $this->addSql('ALTER TABLE training_control DROP FOREIGN KEY FK_30E5BC45BEFD98D1');
        $this->addSql('ALTER TABLE training_control DROP FOREIGN KEY FK_30E5BC4532BEC70E');
        $this->addSql('ALTER TABLE training_compliance_requirement DROP FOREIGN KEY FK_E62BC234BEFD98D1');
        $this->addSql('ALTER TABLE training_compliance_requirement DROP FOREIGN KEY FK_E62BC234492951C7');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E99033212A');
        $this->addSql('ALTER TABLE user_roles DROP FOREIGN KEY FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP FOREIGN KEY FK_54FCD59FD60322AC');
        $this->addSql('ALTER TABLE vulnerabilities DROP FOREIGN KEY FK_459DFAF79033212A');
        $this->addSql('ALTER TABLE vulnerability_asset DROP FOREIGN KEY FK_F83FC91772897D8B');
        $this->addSql('ALTER TABLE vulnerability_asset DROP FOREIGN KEY FK_F83FC9175DA1941');
        $this->addSql('ALTER TABLE workflow_instances DROP FOREIGN KEY FK_878E9AEC2C7C2CBA');
        $this->addSql('ALTER TABLE workflow_instances DROP FOREIGN KEY FK_878E9AECC4EF1FC7');
        $this->addSql('ALTER TABLE workflow_instances DROP FOREIGN KEY FK_878E9AECD9BF9B19');
        $this->addSql('ALTER TABLE workflow_instances DROP FOREIGN KEY FK_878E9AEC9033212A');
        $this->addSql('ALTER TABLE workflow_steps DROP FOREIGN KEY FK_856C7C462C7C2CBA');
        $this->addSql('ALTER TABLE workflow_steps DROP FOREIGN KEY FK_856C7C469033212A');
        $this->addSql('ALTER TABLE workflows DROP FOREIGN KEY FK_EFBFBFC29033212A');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE audit_checklist');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE bc_exercise');
        $this->addSql('DROP TABLE bc_exercise_plan');
        $this->addSql('DROP TABLE bc_exercise_document');
        $this->addSql('DROP TABLE business_continuity_plan');
        $this->addSql('DROP TABLE bc_plan_supplier');
        $this->addSql('DROP TABLE bc_plan_asset');
        $this->addSql('DROP TABLE bc_plan_document');
        $this->addSql('DROP TABLE business_process');
        $this->addSql('DROP TABLE business_process_asset');
        $this->addSql('DROP TABLE business_process_risk');
        $this->addSql('DROP TABLE change_request');
        $this->addSql('DROP TABLE change_request_asset');
        $this->addSql('DROP TABLE change_request_control');
        $this->addSql('DROP TABLE change_request_business_process');
        $this->addSql('DROP TABLE change_request_risk');
        $this->addSql('DROP TABLE change_request_document');
        $this->addSql('DROP TABLE compliance_framework');
        $this->addSql('DROP TABLE compliance_mapping');
        $this->addSql('DROP TABLE compliance_requirement');
        $this->addSql('DROP TABLE compliance_requirement_control');
        $this->addSql('DROP TABLE control');
        $this->addSql('DROP TABLE control_risk');
        $this->addSql('DROP TABLE control_asset');
        $this->addSql('DROP TABLE crisis_teams');
        $this->addSql('DROP TABLE crisis_team_bcp');
        $this->addSql('DROP TABLE cryptographic_operation');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE incident');
        $this->addSql('DROP TABLE incident_control');
        $this->addSql('DROP TABLE incident_asset');
        $this->addSql('DROP TABLE incident_risk');
        $this->addSql('DROP TABLE incident_failed_controls');
        $this->addSql('DROP TABLE interested_party');
        $this->addSql('DROP TABLE internal_audit');
        $this->addSql('DROP TABLE internal_audit_asset');
        $this->addSql('DROP TABLE ismscontext');
        $this->addSql('DROP TABLE ismsobjective');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE management_review');
        $this->addSql('DROP TABLE mfa_tokens');
        $this->addSql('DROP TABLE patches');
        $this->addSql('DROP TABLE patch_asset');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE physical_access_log');
        $this->addSql('DROP TABLE risk');
        $this->addSql('DROP TABLE risk_appetite');
        $this->addSql('DROP TABLE risk_treatment_plan');
        $this->addSql('DROP TABLE risk_treatment_plan_control');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE supplier_asset');
        $this->addSql('DROP TABLE supplier_risk');
        $this->addSql('DROP TABLE supplier_document');
        $this->addSql('DROP TABLE system_settings');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE threat_intelligence');
        $this->addSql('DROP TABLE threat_intelligence_affected_assets');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE training_control');
        $this->addSql('DROP TABLE training_compliance_requirement');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE vulnerabilities');
        $this->addSql('DROP TABLE vulnerability_asset');
        $this->addSql('DROP TABLE workflow_instances');
        $this->addSql('DROP TABLE workflow_steps');
        $this->addSql('DROP TABLE workflows');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
