#!/usr/bin/env python3
r"""
check_translation_dynamic_keys.py — Catalog dynamic-translation-key prefixes.

Many parts of the app build translation keys at runtime:
  Twig :  ('prefix.' ~ var)|trans({}, 'domain')
  PHP  :  $translator->trans('prefix.' . $code, [], 'domain')
  Conf :  ['name_key' => 'prefix.' . $code]

Static linters (debug:translation --only-missing) can't follow these — they
appear as "missing" but are filled at runtime. This gate maintains a
registry under `scripts/quality/dynamic_key_prefixes.txt`. CI regenerates +
diffs against the committed file: a NEW prefix that hasn't been documented
fails the build.

The registry is sorted, one entry per line: `prefix.<short>` + the count.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SKIP_DIRS = {"vendor", "node_modules", "var", ".claude", "tests/Fixtures", "migrations"}

# Twig:   ('prefix.' ~ var)|trans
RE_TWIG = re.compile(
    r"""\(\s*['"]([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)*)\.['"]\s*~\s*\w""",
    re.IGNORECASE,
)
# PHP:    'prefix.' . $var       or   "prefix.{$var}"
RE_PHP_DOT = re.compile(
    r"""['"]([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)*)\.['"]\s*\.\s*\$""",
    re.IGNORECASE,
)
RE_PHP_INTERP = re.compile(
    r"""['"]([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)*)\.\{\$\w""",
    re.IGNORECASE,
)


def is_skipped(path: Path) -> bool:
    parts = path.relative_to(ROOT).parts
    for skip in SKIP_DIRS:
        if "/" in skip:
            seg = tuple(skip.split("/"))
            if any(parts[i:i + len(seg)] == seg for i in range(len(parts))):
                return True
        elif skip in parts:
            return True
    return False


def scan_php(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []
    if "trans(" not in text and "->trans" not in text:
        return []
    return list(set(RE_PHP_DOT.findall(text) + RE_PHP_INTERP.findall(text)))


def scan_twig(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []
    if "|trans" not in text:
        return []
    return list(set(RE_TWIG.findall(text)))


def collect() -> dict[str, int]:
    counter: dict[str, int] = {}
    for f in sorted((ROOT / "src").rglob("*.php")):
        if is_skipped(f):
            continue
        for prefix in scan_php(f):
            counter[prefix] = counter.get(prefix, 0) + 1
    for f in sorted((ROOT / "templates").rglob("*.html.twig")):
        if is_skipped(f):
            continue
        for prefix in scan_twig(f):
            counter[prefix] = counter.get(prefix, 0) + 1
    return counter


def render_registry(counter: dict[str, int]) -> str:
    lines = [
        "# Dynamic translation-key prefix registry — auto-generated by",
        "# scripts/quality/check_translation_dynamic_keys.py.",
        "# Lines are sorted; format: `<prefix>\\t<usage-count>`.",
        "# A NEW prefix in this list will fail CI until committed here.",
        "",
    ]
    for prefix in sorted(counter.keys()):
        lines.append(f"{prefix}\t{counter[prefix]}")
    return "\n".join(lines) + "\n"


def parse_registry(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        parts = s.split("\t", 1)
        if parts:
            out.add(parts[0])
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--baseline",
        type=Path,
        default=ROOT / "scripts" / "quality" / "dynamic_key_prefixes.txt",
        help="Path to registry file (used for both read+diff).",
    )
    ap.add_argument("--write-baseline", type=Path, default=None)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    counter = collect()
    current = set(counter.keys())

    if args.write_baseline is not None:
        args.write_baseline.parent.mkdir(parents=True, exist_ok=True)
        args.write_baseline.write_text(render_registry(counter), encoding="utf-8")
        print(f"check_translation_dynamic_keys: wrote {len(current)} prefixes to {args.write_baseline}")
        return 0

    known = parse_registry(args.baseline)
    new = sorted(current - known)
    stale = sorted(known - current)

    if not new and not stale:
        if not args.quiet:
            print(f"check_translation_dynamic_keys: OK — {len(current)} dynamic prefix(es), all documented.")
        else:
            print(f"check_translation_dynamic_keys: OK ({len(current)})")
        return 0

    if new:
        print("check_translation_dynamic_keys: NEW PREFIXES (not in registry)\n")
        for prefix in new:
            print(f"FAIL prefix '{prefix}' used {counter[prefix]}x — add to {args.baseline}")
    if stale:
        # Stale entries are informational only — registry can be cleaned up
        # but the gate doesn't fail.
        print("\nINFO stale registry entries (no longer used in code):")
        for prefix in stale[:50]:
            print(f"  - {prefix}")
    if new:
        print(
            f"\ncheck_translation_dynamic_keys: {len(new)} new prefix(es) without doc.\n"
            "Fix: regenerate registry with:\n"
            "    python3 scripts/quality/check_translation_dynamic_keys.py "
            "--write-baseline scripts/quality/dynamic_key_prefixes.txt"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
