<?php

declare(strict_types=1);

namespace App\Service\ComplianceWizard\Check\PolicyWizard\Bsi;

use App\Entity\PolicyTemplate;
use App\Entity\Tenant;
use App\Repository\DocumentRepository;
use App\Repository\PolicyTemplateRepository;
use App\Service\ComplianceWizard\Check\PolicyWizard\PolicyWizardCheckInterface;
use App\Service\ComplianceWizard\Check\PolicyWizard\PolicyWizardCheckResult;

/**
 * W5-C / BSI 200-2 Basis-Absicherung — confirms every active BSI
 * Basis-tier policy template has a corresponding tenant Document
 * generated by the Policy-Wizard.
 *
 * Per `docs/plans/policy-wizard/02-bsi-input.md` §1237 the baseline
 * tier ships with 28 Pflicht-Richtlinien + 1 Schutzbedarfsfeststellungs-
 * Methode. This check enforces topic-coverage across the Basis tier:
 * for every template marked `bsiTier='basis'` and `standard='bsi'`,
 * the tenant MUST own at least one published/approved Document
 * generated from that template.
 *
 * Topics where the tenant has no Document yet are listed as gaps so
 * the wizard can re-run the missing topics in a single click.
 */
final class BsiBaselineCoverageCheck implements PolicyWizardCheckInterface
{
    public const CHECK_ID = 'bsi_baseline_coverage';
    private const STANDARD = 'bsi';

    public function __construct(
        private readonly DocumentRepository $documentRepository,
        private readonly PolicyTemplateRepository $templateRepository,
    ) {
    }

    public function getCheckId(): string
    {
        return self::CHECK_ID;
    }

    public function getStandard(): string
    {
        return self::STANDARD;
    }

    public function run(?Tenant $tenant): PolicyWizardCheckResult
    {
        if ($tenant === null) {
            return new PolicyWizardCheckResult(
                checkId: self::CHECK_ID,
                score: 0.0,
                passed: false,
                details: ['reason' => 'no_tenant'],
            );
        }

        /** @var list<PolicyTemplate> $basisTemplates */
        $basisTemplates = $this->templateRepository->findBy([
            'standard' => self::STANDARD,
            'bsiTier' => PolicyTemplate::BSI_TIER_BASIS,
        ]);

        $expected = count($basisTemplates);
        if ($expected === 0) {
            // No Basis templates seeded yet — vacuously satisfied. The
            // seed-templates command (W5-A) populates them; until that
            // runs we cannot fail the tenant for missing artefacts.
            return new PolicyWizardCheckResult(
                checkId: self::CHECK_ID,
                score: 100.0,
                passed: true,
                details: [
                    'expected_topics' => 0,
                    'reason' => 'no_basis_templates_seeded',
                ],
            );
        }

        $coveredTopics = [];
        $missingTopics = [];
        foreach ($basisTemplates as $template) {
            $topic = $template->getTopic();
            if ($topic === null) {
                continue;
            }
            $count = (int) $this->documentRepository->createQueryBuilder('d')
                ->select('COUNT(d.id)')
                ->innerJoin('d.generatedFromTemplate', 't')
                ->where('d.tenant = :tenant')
                ->andWhere('d.status IN (:statuses)')
                ->andWhere('d.isArchived = false')
                ->andWhere('t.standard = :standard')
                ->andWhere('t.topic = :topic')
                ->setParameter('tenant', $tenant)
                ->setParameter('statuses', ['published', 'approved'])
                ->setParameter('standard', self::STANDARD)
                ->setParameter('topic', $topic)
                ->getQuery()
                ->getSingleScalarResult();

            if ($count > 0) {
                $coveredTopics[] = $topic;
            } else {
                $missingTopics[] = $topic;
            }
        }

        $covered = count($coveredTopics);
        if ($missingTopics === []) {
            return new PolicyWizardCheckResult(
                checkId: self::CHECK_ID,
                score: 100.0,
                passed: true,
                details: [
                    'expected_topics' => $expected,
                    'covered_topics' => $covered,
                ],
            );
        }

        $score = round(($covered / $expected) * 100, 1);
        return new PolicyWizardCheckResult(
            checkId: self::CHECK_ID,
            score: $score,
            passed: false,
            details: [
                'expected_topics' => $expected,
                'covered_topics' => $covered,
                'missing_count' => count($missingTopics),
            ],
            gap: [
                'title' => sprintf('compliance_check.%s.fail_message', self::CHECK_ID),
                'priority' => 'critical',
                'route' => 'app_policy_wizard_index',
                'translation_domain' => 'policy_wizard',
                'items' => array_slice($missingTopics, 0, 5),
            ],
        );
    }
}
