<?php

declare(strict_types=1);

namespace App\Service\ComplianceWizard\Check\PolicyWizard;

use App\Entity\Tenant;
use App\Repository\DocumentRepository;

/**
 * Confirms the tenant has a published topic-specific policy generated by the
 * Policy-Wizard for ONE configured topic-key (e.g. `access_control`).
 *
 * Parameterised check — `config/services.yaml` registers 24 instances, one
 * per ISO 27002:2022 topic listed in
 * {@see PolicyWizardTopicCatalogue::ISO27001_TOPICS}. Building 24 hand-rolled
 * classes would be repetitive and would break the data-reuse principle —
 * hence the factory pattern. Reference: `01-iso27001-input.md` §2.
 */
final class PolicyTopicPresentCheck implements PolicyWizardCheckInterface
{
    public function __construct(
        private readonly DocumentRepository $documentRepository,
        private readonly string $topic,
        private readonly string $standard = 'iso27001',
    ) {
        if ($this->topic === '') {
            throw new \App\Exception\InvalidArgument\InvalidArgumentException('PolicyTopicPresentCheck requires a non-empty topic.', 'topic');
        }
    }

    public function getCheckId(): string
    {
        return sprintf('policy_topic_%s_present', $this->topic);
    }

    public function getStandard(): string
    {
        return $this->standard;
    }

    public function getTopic(): string
    {
        return $this->topic;
    }

    public function run(?Tenant $tenant): PolicyWizardCheckResult
    {
        $checkId = $this->getCheckId();

        if ($tenant === null) {
            return new PolicyWizardCheckResult(
                checkId: $checkId,
                score: 0.0,
                passed: false,
                details: ['reason' => 'no_tenant', 'topic' => $this->topic],
            );
        }

        $count = (int) $this->documentRepository->createQueryBuilder('d')
            ->select('COUNT(d.id)')
            ->innerJoin('d.generatedFromTemplate', 't')
            ->where('d.tenant = :tenant')
            ->andWhere('d.status IN (:statuses)')
            ->andWhere('d.isArchived = false')
            ->andWhere('t.standard = :standard')
            ->andWhere('t.topic = :topic')
            ->setParameter('tenant', $tenant)
            ->setParameter('statuses', ['published', 'approved'])
            ->setParameter('standard', $this->standard)
            ->setParameter('topic', $this->topic)
            ->getQuery()
            ->getSingleScalarResult();

        if ($count > 0) {
            return new PolicyWizardCheckResult(
                checkId: $checkId,
                score: 100.0,
                passed: true,
                details: ['published_documents' => $count, 'topic' => $this->topic],
            );
        }

        return new PolicyWizardCheckResult(
            checkId: $checkId,
            score: 0.0,
            passed: false,
            details: ['published_documents' => 0, 'topic' => $this->topic],
            gap: [
                'title' => sprintf('compliance_check.%s.fail_message', $checkId),
                'priority' => 'high',
                'route' => 'app_policy_wizard_index',
                'translation_domain' => 'policy_wizard',
            ],
        );
    }
}
