<?php

declare(strict_types=1);

namespace App\Service\ComplianceWizard\Check\PolicyWizard;

use App\Entity\Tenant;
use App\Repository\DocumentRepository;

/**
 * Confirms the tenant has a published Top-Level Information Security Policy
 * (the ISO 27001 Cl. 5.2 ISMS-Leitlinie) generated by the Policy-Wizard.
 *
 * A document qualifies when ALL of the following hold:
 * - `tenant` matches
 * - `status` is `published` or `approved`
 * - `isArchived` is false
 * - `generatedFromTemplate` has `standard='iso27001'` and
 *   `topic='top_level'`
 *
 * Reference: `01-iso27001-input.md` §1 (top-level policy) +
 * Compliance-Manager review §"What worries me" #6.
 */
final class PolicyTopLevelPresentCheck implements PolicyWizardCheckInterface
{
    public const CHECK_ID = 'policy_top_level_present';
    private const STANDARD = 'iso27001';
    private const TOPIC = 'top_level';

    public function __construct(
        private readonly DocumentRepository $documentRepository,
    ) {
    }

    public function getCheckId(): string
    {
        return self::CHECK_ID;
    }

    public function getStandard(): string
    {
        return self::STANDARD;
    }

    public function run(?Tenant $tenant): PolicyWizardCheckResult
    {
        if ($tenant === null) {
            return new PolicyWizardCheckResult(
                checkId: self::CHECK_ID,
                score: 0.0,
                passed: false,
                details: ['reason' => 'no_tenant'],
            );
        }

        $count = (int) $this->documentRepository->createQueryBuilder('d')
            ->select('COUNT(d.id)')
            ->innerJoin('d.generatedFromTemplate', 't')
            ->where('d.tenant = :tenant')
            ->andWhere('d.status IN (:statuses)')
            ->andWhere('d.isArchived = false')
            ->andWhere('t.standard = :standard')
            ->andWhere('t.topic = :topic')
            ->setParameter('tenant', $tenant)
            ->setParameter('statuses', ['published', 'approved'])
            ->setParameter('standard', self::STANDARD)
            ->setParameter('topic', self::TOPIC)
            ->getQuery()
            ->getSingleScalarResult();

        if ($count > 0) {
            return new PolicyWizardCheckResult(
                checkId: self::CHECK_ID,
                score: 100.0,
                passed: true,
                details: ['published_documents' => $count],
            );
        }

        return new PolicyWizardCheckResult(
            checkId: self::CHECK_ID,
            score: 0.0,
            passed: false,
            details: ['published_documents' => 0],
            gap: [
                'title' => 'compliance_check.policy_top_level_present.fail_message',
                'priority' => 'critical',
                'route' => 'app_policy_wizard_index',
                'translation_domain' => 'policy_wizard',
            ],
        );
    }
}
