import { test, expect, type Page } from '@playwright/test';
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import yaml from 'js-yaml';
import { loginAs } from '../fixtures/auth';

/**
 * L1 Browser-Smoke: navigates every GET-able route the route-exporter found
 * and asserts the page renders without a 5xx, without unexpected console
 * errors, and without an unexpected "Modul nicht aktiv" banner.
 *
 * Data sources:
 *   - `var/browser-coverage/routes.json`   — generated by
 *     `php bin/console app:browser-coverage:export-routes`
 *   - `tests/E2e/coverage/persona-routes.yaml` — persona × allow-pattern matrix
 *
 * Output:
 *   - JSON report:    `var/browser-coverage/results/<persona>.json`
 *   - Screenshots on fail: under Playwright's outputDir
 *
 * The route-coverage run is intentionally `continue-on-error` in CI: the
 * goal is broad signal, not a per-route block. The aggregator
 * (`scripts/browser-coverage/generate-report.mjs`) turns the JSON outputs
 * into a per-persona HTML report.
 */

const PROJECT_ROOT = resolve(__dirname, '..', '..', '..');
const ROUTES_JSON = process.env.BROWSER_COVERAGE_ROUTES
    ?? resolve(PROJECT_ROOT, 'var/browser-coverage/routes.json');
const PERSONA_YAML = resolve(PROJECT_ROOT, 'tests/E2e/coverage/persona-routes.yaml');
const RESULTS_DIR = resolve(PROJECT_ROOT, 'var/browser-coverage/results');

interface RouteEntry {
    name: string;
    path: string;
    raw: string;
    methods: string[];
    admin: boolean;
    category: string;
}

interface PersonaSpec {
    label: string;
    expects?: number;
    allow_patterns: string[];
    deny_patterns?: string[];
    extra_routes?: string[];
}

interface RoutesPayload {
    generated_at: string;
    count: number;
    routes: RouteEntry[];
}

interface PersonasPayload {
    defaults: { global_deny: string[] };
    personas: Record<string, PersonaSpec>;
}

interface RouteResult {
    persona: string;
    path: string;
    name: string;
    category: string;
    status: number | null;
    durationMs: number;
    consoleErrors: string[];
    pageErrors: string[];
    failedRequests: string[];   // sub-resource (asset/AJAX) 4xx/5xx hits
    bannerSeen: boolean;
    ok: boolean;
    reason?: string;
}

const DEFAULT_PERSONA = process.env.BROWSER_COVERAGE_PERSONA || 'full-sweep';

function loadConfig(): { routes: RouteEntry[]; persona: PersonaSpec; globalDeny: string[] } {
    if (!existsSync(ROUTES_JSON)) {
        throw new Error(
            `Routes manifest missing at ${ROUTES_JSON}. Run "php bin/console app:browser-coverage:export-routes" first.`,
        );
    }
    const routesPayload = JSON.parse(readFileSync(ROUTES_JSON, 'utf8')) as RoutesPayload;
    const personasPayload = yaml.load(readFileSync(PERSONA_YAML, 'utf8')) as PersonasPayload;

    const persona = personasPayload.personas[DEFAULT_PERSONA];
    if (!persona) {
        throw new Error(
            `Persona "${DEFAULT_PERSONA}" not found in ${PERSONA_YAML}. Available: ${Object.keys(personasPayload.personas).join(', ')}`,
        );
    }

    return {
        routes: routesPayload.routes,
        persona,
        globalDeny: personasPayload.defaults?.global_deny ?? [],
    };
}

function applyPersonaFilter(routes: RouteEntry[], persona: PersonaSpec, globalDeny: string[]): RouteEntry[] {
    return routes.filter((r) => {
        for (const pat of globalDeny) {
            if (r.path.includes(pat)) return false;
        }
        for (const pat of persona.deny_patterns ?? []) {
            if (r.path.includes(pat)) return false;
        }
        if (persona.allow_patterns.length === 0) return true;
        for (const pat of persona.allow_patterns) {
            if (pat === '/' || r.path.includes(pat)) return true;
        }
        return false;
    });
}

async function probeOne(page: Page, route: RouteEntry): Promise<RouteResult> {
    const consoleErrors: string[] = [];
    const pageErrors: string[] = [];
    const failedRequests: string[] = [];

    const consoleHandler = (msg: { type(): string; text(): string }): void => {
        if (msg.type() === 'error') {
            consoleErrors.push(msg.text());
        }
    };
    const pageErrorHandler = (err: Error): void => {
        pageErrors.push(err.message);
    };
    // Catch sub-resource failures (CSS/JS/AJAX 4xx/5xx). These surface as
    // broken UI / missing icons / dead Stimulus controllers even when the
    // page itself returns 200. Skip the navigation response itself, dev-tool
    // sidecar URLs, and well-known harmless 404s (favicon).
    const responseHandler = (resp: { status(): number; url(): string; request(): { resourceType(): string } }): void => {
        const code = resp.status();
        if (code < 400) return;
        const url = resp.url();
        if (url.endsWith(route.path)) return;
        if (url.startsWith('chrome-extension://') || url.startsWith('devtools://')) return;
        if (url.endsWith('/favicon.ico')) return;
        failedRequests.push(`[${code}] ${resp.request().resourceType()} ${url}`);
    };

    page.on('console', consoleHandler);
    page.on('pageerror', pageErrorHandler);
    page.on('response', responseHandler);

    const t0 = Date.now();
    let status: number | null = null;
    let reason: string | undefined;
    let isDownload = false;

    try {
        const response = await page.goto(route.path, { waitUntil: 'domcontentloaded', timeout: 20_000 });
        status = response?.status() ?? null;
    } catch (err) {
        const msg = (err as Error).message;
        // Playwright throws "Download is starting" when navigating to a route
        // that serves a streamed file (PDF/Excel/CSV/ZIP). Counts as success —
        // the server did NOT 5xx, it just returned a non-HTML body.
        if (msg.includes('Download is starting')) {
            isDownload = true;
            status = 200;
        } else {
            reason = msg;
        }
    } finally {
        page.off('console', consoleHandler);
        page.off('pageerror', pageErrorHandler);
        page.off('response', responseHandler);
    }

    const durationMs = Date.now() - t0;

    // Detect "Module inactive" banner — when persona expected 200 but the
    // module is off, the route returns 200 with the inactive-banner. That
    // is a coverage signal, not a hard failure. Skip on download routes
    // where the page has no DOM to inspect.
    let bannerSeen = false;
    if (!isDownload) {
        try {
            bannerSeen = await page.locator('text=ist nicht aktiviert').first().isVisible({ timeout: 250 });
        } catch {
            bannerSeen = false;
        }
    }

    const is5xx = status !== null && status >= 500;
    const ok = status !== null
        && status < 500
        && pageErrors.length === 0
        && failedRequests.length === 0;

    const reasonParts: string[] = [];
    if (reason) reasonParts.push(reason);
    if (is5xx) reasonParts.push(`HTTP ${status}`);
    if (failedRequests.length > 0) reasonParts.push(`${failedRequests.length} sub-request fail`);

    return {
        persona: DEFAULT_PERSONA,
        path: route.path,
        name: route.name,
        category: route.category,
        status,
        durationMs,
        consoleErrors,
        pageErrors,
        failedRequests,
        bannerSeen,
        ok,
        reason: reasonParts.length > 0 ? reasonParts.join('; ') : undefined,
    };
}

// Do NOT use `serial` describe-mode — it bails the run on first failure
// and skips every subsequent route, defeating the broad-coverage purpose.
// `workers=1` in playwright.config.ts already keeps execution sequential.

// Skip the entire describe-block in regular `npm run e2e` runs — the smoke
// spec only fires when the route-export has run or the operator opted in
// via `BROWSER_COVERAGE_PERSONA`. Without that signal the spec would crash
// on module-load looking for routes.json the regular flow never produces.
const smokeEnabled = !!process.env.BROWSER_COVERAGE_PERSONA || existsSync(ROUTES_JSON);

test.describe(`L1 Browser-Smoke — ${DEFAULT_PERSONA}`, () => {
    if (!smokeEnabled) {
        test('skipped — set BROWSER_COVERAGE_PERSONA or run app:browser-coverage:export-routes to enable', () => {
            test.skip(true, 'L1 smoke disabled (no BROWSER_COVERAGE_PERSONA env, no routes.json).');
        });
        return;
    }

    const { routes, persona, globalDeny } = loadConfig();
    const filtered = applyPersonaFilter(routes, persona, globalDeny);

    if (filtered.length === 0) {
        test('no routes matched persona filter — nothing to test', () => {
            test.skip(true, `No routes matched persona "${DEFAULT_PERSONA}".`);
        });
        return;
    }

    const results: RouteResult[] = [];

    test.beforeAll(async () => {
        mkdirSync(RESULTS_DIR, { recursive: true });
    });

    test.afterAll(async () => {
        const summary = {
            persona: DEFAULT_PERSONA,
            label: persona.label,
            ran_at: new Date().toISOString(),
            total: results.length,
            ok: results.filter((r) => r.ok).length,
            failed: results.filter((r) => !r.ok).length,
            module_banner: results.filter((r) => r.bannerSeen).length,
            results,
        };
        const outPath = resolve(RESULTS_DIR, `${DEFAULT_PERSONA}.json`);
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, JSON.stringify(summary, null, 2));
        console.log(`\n[L1 smoke] ${DEFAULT_PERSONA}: ${summary.ok}/${summary.total} ok → ${outPath}`);
    });

    for (const route of filtered) {
        test(`${route.category} | ${route.path} (${route.name})`, async ({ page }) => {
            await loginAs(page);
            const result = await probeOne(page, route);
            results.push(result);

            // Hard-fail the test only on 5xx or page-errors (real bugs).
            // Console errors / banners surface in the report but don't block.
            expect.soft(result.status, `HTTP status for ${route.path}`).not.toBe(500);
            expect.soft(result.pageErrors, `Page errors on ${route.path}`).toEqual([]);
            expect.soft(
                result.failedRequests,
                `Sub-resource fails on ${route.path}`,
            ).toEqual([]);
        });
    }
});
